from .jbz_pkg import Ui_pkg_widget
from .main import Ui_MainWindow
from .emv import Ui_emv_widget
from .tms_param import Ui_tms_widget
from .jfrog import Ui_jfrog_widget
from .save_on_screen_data import Ui_save_widget
from .load_to_screen import Ui_load_widget
from .map import Ui_map_widget
from .compare import Ui_compare_widget
