# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jbz_pkg.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pkg_widget(object):
    def setupUi(self, pkg_widget):
        pkg_widget.setObjectName("pkg_widget")
        pkg_widget.resize(878, 249)
        self.verticalLayout = QtWidgets.QVBoxLayout(pkg_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(pkg_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(pkg_widget)
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.jbzPathPushButton = QtWidgets.QPushButton(self.frame)
        self.jbzPathPushButton.setObjectName("jbzPathPushButton")
        self.gridLayout.addWidget(self.jbzPathPushButton, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.sevenZpushButton = QtWidgets.QPushButton(self.frame)
        self.sevenZpushButton.setObjectName("sevenZpushButton")
        self.gridLayout.addWidget(self.sevenZpushButton, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.extractionPathLineEdit = QtWidgets.QLineEdit(self.frame)
        self.extractionPathLineEdit.setObjectName("extractionPathLineEdit")
        self.gridLayout.addWidget(self.extractionPathLineEdit, 1, 1, 1, 1)
        self.sevenZlineEdit = QtWidgets.QLineEdit(self.frame)
        self.sevenZlineEdit.setObjectName("sevenZlineEdit")
        self.gridLayout.addWidget(self.sevenZlineEdit, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.jbz_manifest_line_edit = QtWidgets.QLineEdit(self.frame)
        self.jbz_manifest_line_edit.setObjectName("jbz_manifest_line_edit")
        self.gridLayout.addWidget(self.jbz_manifest_line_edit, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.jbzPathLineEdit = QtWidgets.QLineEdit(self.frame)
        self.jbzPathLineEdit.setEnabled(True)
        self.jbzPathLineEdit.setObjectName("jbzPathLineEdit")
        self.gridLayout.addWidget(self.jbzPathLineEdit, 0, 1, 1, 1)
        self.extractionPushButton = QtWidgets.QPushButton(self.frame)
        self.extractionPushButton.setObjectName("extractionPushButton")
        self.gridLayout.addWidget(self.extractionPushButton, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.jbz_regex_match_ver_line_edit = QtWidgets.QLineEdit(self.frame)
        self.jbz_regex_match_ver_line_edit.setObjectName("jbz_regex_match_ver_line_edit")
        self.gridLayout.addWidget(self.jbz_regex_match_ver_line_edit, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.extractPushButton = QtWidgets.QPushButton(pkg_widget)
        self.extractPushButton.setObjectName("extractPushButton")
        self.horizontalLayout_3.addWidget(self.extractPushButton)
        self.closePushButton = QtWidgets.QPushButton(pkg_widget)
        self.closePushButton.setObjectName("closePushButton")
        self.horizontalLayout_3.addWidget(self.closePushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(pkg_widget)
        self.closePushButton.clicked.connect(pkg_widget.hide)
        QtCore.QMetaObject.connectSlotsByName(pkg_widget)

    def retranslateUi(self, pkg_widget):
        _translate = QtCore.QCoreApplication.translate
        pkg_widget.setWindowTitle(_translate("pkg_widget", "Job Bundle Package Version"))
        self.label.setText(_translate("pkg_widget", "Job Bundle Package Version"))
        self.jbzPathPushButton.setText(_translate("pkg_widget", "Search"))
        self.label_2.setText(_translate("pkg_widget", "Job Bundle File Path"))
        self.sevenZpushButton.setText(_translate("pkg_widget", "Search"))
        self.label_4.setText(_translate("pkg_widget", "7z Path"))
        self.label_5.setText(_translate("pkg_widget", "Manifest File"))
        self.extractionPushButton.setText(_translate("pkg_widget", "Search"))
        self.label_3.setText(_translate("pkg_widget", "Extraction File Path"))
        self.label_6.setText(_translate("pkg_widget", "Version Regex"))
        self.extractPushButton.setText(_translate("pkg_widget", "Extract"))
        self.closePushButton.setText(_translate("pkg_widget", "Close"))
