# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jfrog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1123, 139)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.jfrog_browse_push_button = QtWidgets.QPushButton(self.frame)
        self.jfrog_browse_push_button.setObjectName("jfrog_browse_push_button")
        self.gridLayout.addWidget(self.jfrog_browse_push_button, 0, 2, 1, 1)
        self.jfrog_label = QtWidgets.QLabel(self.frame)
        self.jfrog_label.setObjectName("jfrog_label")
        self.gridLayout.addWidget(self.jfrog_label, 0, 0, 1, 1)
        self.jfrog_line_edit = QtWidgets.QLineEdit(self.frame)
        self.jfrog_line_edit.setEnabled(True)
        self.jfrog_line_edit.setObjectName("jfrog_line_edit")
        self.gridLayout.addWidget(self.jfrog_line_edit, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.jfrog_load_push_button = QtWidgets.QPushButton(Form)
        self.jfrog_load_push_button.setObjectName("jfrog_load_push_button")
        self.horizontalLayout_3.addWidget(self.jfrog_load_push_button)
        self.jfrog_close_push_button = QtWidgets.QPushButton(Form)
        self.jfrog_close_push_button.setObjectName("jfrog_close_push_button")
        self.horizontalLayout_3.addWidget(self.jfrog_close_push_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "JFrog Artifactory"))
        self.jfrog_browse_push_button.setText(_translate("Form", "Browse"))
        self.jfrog_label.setText(_translate("Form", "URL"))
        self.jfrog_load_push_button.setText(_translate("Form", "Load"))
        self.jfrog_close_push_button.setText(_translate("Form", "Close"))
