# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jfrog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jfrog_widget(object):
    def setupUi(self, jfrog_widget):
        jfrog_widget.setObjectName("jfrog_widget")
        jfrog_widget.resize(663, 448)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("vc.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        jfrog_widget.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(jfrog_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(jfrog_widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(jfrog_widget)
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.jfrog_version_combo_box = QtWidgets.QComboBox(self.frame)
        self.jfrog_version_combo_box.setObjectName("jfrog_version_combo_box")
        self.horizontalLayout_2.addWidget(self.jfrog_version_combo_box)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.jfrog_download_all_push_button = QtWidgets.QPushButton(self.frame)
        self.jfrog_download_all_push_button.setObjectName("jfrog_download_all_push_button")
        self.horizontalLayout_2.addWidget(self.jfrog_download_all_push_button)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.jfrog_all_tableview = QtWidgets.QTableView(self.frame)
        self.jfrog_all_tableview.setObjectName("jfrog_all_tableview")
        self.gridLayout.addWidget(self.jfrog_all_tableview, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.jfrog_type_check_box = QtWidgets.QCheckBox(jfrog_widget)
        self.jfrog_type_check_box.setChecked(True)
        self.jfrog_type_check_box.setObjectName("jfrog_type_check_box")
        self.horizontalLayout_3.addWidget(self.jfrog_type_check_box)
        self.jfrog_size_check_box = QtWidgets.QCheckBox(jfrog_widget)
        self.jfrog_size_check_box.setChecked(True)
        self.jfrog_size_check_box.setObjectName("jfrog_size_check_box")
        self.horizontalLayout_3.addWidget(self.jfrog_size_check_box)
        self.jfrog_created_check_box = QtWidgets.QCheckBox(jfrog_widget)
        self.jfrog_created_check_box.setChecked(True)
        self.jfrog_created_check_box.setObjectName("jfrog_created_check_box")
        self.horizontalLayout_3.addWidget(self.jfrog_created_check_box)
        self.jfrog_modified_check_box = QtWidgets.QCheckBox(jfrog_widget)
        self.jfrog_modified_check_box.setChecked(True)
        self.jfrog_modified_check_box.setObjectName("jfrog_modified_check_box")
        self.horizontalLayout_3.addWidget(self.jfrog_modified_check_box)
        self.jfrog_sha1_check_box = QtWidgets.QCheckBox(jfrog_widget)
        self.jfrog_sha1_check_box.setChecked(True)
        self.jfrog_sha1_check_box.setObjectName("jfrog_sha1_check_box")
        self.horizontalLayout_3.addWidget(self.jfrog_sha1_check_box)
        self.jfrog_md5_check_box = QtWidgets.QCheckBox(jfrog_widget)
        self.jfrog_md5_check_box.setChecked(True)
        self.jfrog_md5_check_box.setObjectName("jfrog_md5_check_box")
        self.horizontalLayout_3.addWidget(self.jfrog_md5_check_box)
        self.jfrog_props_check_box = QtWidgets.QCheckBox(jfrog_widget)
        self.jfrog_props_check_box.setChecked(True)
        self.jfrog_props_check_box.setObjectName("jfrog_props_check_box")
        self.horizontalLayout_3.addWidget(self.jfrog_props_check_box)
        self.jfrog_filter_push_button = QtWidgets.QPushButton(jfrog_widget)
        self.jfrog_filter_push_button.setObjectName("jfrog_filter_push_button")
        self.horizontalLayout_3.addWidget(self.jfrog_filter_push_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.jfrog_download_push_button = QtWidgets.QPushButton(jfrog_widget)
        self.jfrog_download_push_button.setObjectName("jfrog_download_push_button")
        self.horizontalLayout_3.addWidget(self.jfrog_download_push_button)
        self.jfrog_main_push_button = QtWidgets.QPushButton(jfrog_widget)
        self.jfrog_main_push_button.setObjectName("jfrog_main_push_button")
        self.horizontalLayout_3.addWidget(self.jfrog_main_push_button)
        self.jfrog_close_push_button = QtWidgets.QPushButton(jfrog_widget)
        self.jfrog_close_push_button.setObjectName("jfrog_close_push_button")
        self.horizontalLayout_3.addWidget(self.jfrog_close_push_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(jfrog_widget)
        self.jfrog_close_push_button.clicked.connect(jfrog_widget.close)
        QtCore.QMetaObject.connectSlotsByName(jfrog_widget)

    def retranslateUi(self, jfrog_widget):
        _translate = QtCore.QCoreApplication.translate
        jfrog_widget.setWindowTitle(_translate("jfrog_widget", "JFrog Artifactory"))
        self.label.setText(_translate("jfrog_widget", "JFrog Artifactory"))
        self.label_2.setText(_translate("jfrog_widget", "Build version"))
        self.jfrog_download_all_push_button.setText(_translate("jfrog_widget", "Download All"))
        self.jfrog_type_check_box.setText(_translate("jfrog_widget", "type"))
        self.jfrog_size_check_box.setText(_translate("jfrog_widget", "size"))
        self.jfrog_created_check_box.setText(_translate("jfrog_widget", "created"))
        self.jfrog_modified_check_box.setText(_translate("jfrog_widget", "modified"))
        self.jfrog_sha1_check_box.setText(_translate("jfrog_widget", "sha1"))
        self.jfrog_md5_check_box.setText(_translate("jfrog_widget", "md5"))
        self.jfrog_props_check_box.setText(_translate("jfrog_widget", "props"))
        self.jfrog_filter_push_button.setText(_translate("jfrog_widget", "Filter"))
        self.jfrog_download_push_button.setText(_translate("jfrog_widget", "Download"))
        self.jfrog_main_push_button.setText(_translate("jfrog_widget", "Main"))
        self.jfrog_close_push_button.setText(_translate("jfrog_widget", "Close"))
