# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'map.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_map_widget(object):
    def setupUi(self, map_widget):
        map_widget.setObjectName("map_widget")
        map_widget.resize(1103, 673)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("vc.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        map_widget.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(map_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.map_emv_label = QtWidgets.QLabel(map_widget)
        self.map_emv_label.setObjectName("map_emv_label")
        self.verticalLayout_4.addWidget(self.map_emv_label)
        self.map_emv_table = QtWidgets.QTableView(map_widget)
        self.map_emv_table.setObjectName("map_emv_table")
        self.verticalLayout_4.addWidget(self.map_emv_table)
        self.map_emv_line_edit = QtWidgets.QLineEdit(map_widget)
        self.map_emv_line_edit.setObjectName("map_emv_line_edit")
        self.verticalLayout_4.addWidget(self.map_emv_line_edit)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 2, 1, 1)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.map_manifest_label = QtWidgets.QLabel(map_widget)
        self.map_manifest_label.setObjectName("map_manifest_label")
        self.verticalLayout_21.addWidget(self.map_manifest_label)
        self.map_manifest_table = QtWidgets.QTableView(map_widget)
        self.map_manifest_table.setObjectName("map_manifest_table")
        self.verticalLayout_21.addWidget(self.map_manifest_table)
        self.map_manifest_line_edit = QtWidgets.QLineEdit(map_widget)
        self.map_manifest_line_edit.setObjectName("map_manifest_line_edit")
        self.verticalLayout_21.addWidget(self.map_manifest_line_edit)
        self.gridLayout.addLayout(self.verticalLayout_21, 0, 1, 1, 1)
        self.map_rule_table = QtWidgets.QTableView(map_widget)
        self.map_rule_table.setObjectName("map_rule_table")
        self.gridLayout.addWidget(self.map_rule_table, 1, 0, 1, 5)
        self.frame = QtWidgets.QFrame(map_widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.map_rule_name_label = QtWidgets.QLabel(self.frame)
        self.map_rule_name_label.setObjectName("map_rule_name_label")
        self.horizontalLayout.addWidget(self.map_rule_name_label)
        self.map_rule_name_line_edit = QtWidgets.QLineEdit(self.frame)
        self.map_rule_name_line_edit.setObjectName("map_rule_name_line_edit")
        self.horizontalLayout.addWidget(self.map_rule_name_line_edit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.map_save_push_button = QtWidgets.QPushButton(self.frame)
        self.map_save_push_button.setObjectName("map_save_push_button")
        self.horizontalLayout.addWidget(self.map_save_push_button)
        self.map_close_push_button = QtWidgets.QPushButton(self.frame)
        self.map_close_push_button.setObjectName("map_close_push_button")
        self.horizontalLayout.addWidget(self.map_close_push_button)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 5)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.map_pkg_ver_label = QtWidgets.QLabel(map_widget)
        self.map_pkg_ver_label.setObjectName("map_pkg_ver_label")
        self.verticalLayout_22.addWidget(self.map_pkg_ver_label)
        self.map_pkg_table = QtWidgets.QTableView(map_widget)
        self.map_pkg_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.map_pkg_table.setObjectName("map_pkg_table")
        self.verticalLayout_22.addWidget(self.map_pkg_table)
        self.map_pkg_ver_line_edit = QtWidgets.QLineEdit(map_widget)
        self.map_pkg_ver_line_edit.setObjectName("map_pkg_ver_line_edit")
        self.verticalLayout_22.addWidget(self.map_pkg_ver_line_edit)
        self.gridLayout.addLayout(self.verticalLayout_22, 0, 0, 1, 1)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.map_tms_label = QtWidgets.QLabel(map_widget)
        self.map_tms_label.setObjectName("map_tms_label")
        self.verticalLayout_20.addWidget(self.map_tms_label)
        self.map_tms_table = QtWidgets.QTableView(map_widget)
        self.map_tms_table.setObjectName("map_tms_table")
        self.verticalLayout_20.addWidget(self.map_tms_table)
        self.map_tms_line_edit = QtWidgets.QLineEdit(map_widget)
        self.map_tms_line_edit.setObjectName("map_tms_line_edit")
        self.verticalLayout_20.addWidget(self.map_tms_line_edit)
        self.gridLayout.addLayout(self.verticalLayout_20, 0, 3, 1, 2)

        self.retranslateUi(map_widget)
        self.map_close_push_button.clicked.connect(map_widget.hide)
        QtCore.QMetaObject.connectSlotsByName(map_widget)

    def retranslateUi(self, map_widget):
        _translate = QtCore.QCoreApplication.translate
        map_widget.setWindowTitle(_translate("map_widget", "Map Filter Rules"))
        self.map_emv_label.setText(_translate("map_widget", "EMV Kernel Version"))
        self.map_manifest_label.setText(_translate("map_widget", "Manifest File"))
        self.map_rule_name_label.setText(_translate("map_widget", "Name"))
        self.map_save_push_button.setText(_translate("map_widget", "Save"))
        self.map_close_push_button.setText(_translate("map_widget", "Close"))
        self.map_pkg_ver_label.setText(_translate("map_widget", "Package Version"))
        self.map_tms_label.setText(_translate("map_widget", "TMSLite Parameters"))
