# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settings_widget(object):
    def setupUi(self, settings_widget):
        settings_widget.setObjectName("settings_widget")
        settings_widget.resize(936, 326)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("vc.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        settings_widget.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(settings_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pkg_ver_group_box = QtWidgets.QGroupBox(settings_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pkg_ver_group_box.setFont(font)
        self.pkg_ver_group_box.setAutoFillBackground(False)
        self.pkg_ver_group_box.setAlignment(QtCore.Qt.AlignCenter)
        self.pkg_ver_group_box.setFlat(False)
        self.pkg_ver_group_box.setObjectName("pkg_ver_group_box")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.pkg_ver_group_box)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.settings_extract_path_label = QtWidgets.QLabel(self.pkg_ver_group_box)
        self.settings_extract_path_label.setObjectName("settings_extract_path_label")
        self.gridLayout_8.addWidget(self.settings_extract_path_label, 0, 0, 1, 1)
        self.settings_seven_zip_line_edit = QtWidgets.QLineEdit(self.pkg_ver_group_box)
        self.settings_seven_zip_line_edit.setObjectName("settings_seven_zip_line_edit")
        self.gridLayout_8.addWidget(self.settings_seven_zip_line_edit, 1, 1, 1, 1)
        self.settings_mnf_file_label = QtWidgets.QLabel(self.pkg_ver_group_box)
        self.settings_mnf_file_label.setObjectName("settings_mnf_file_label")
        self.gridLayout_8.addWidget(self.settings_mnf_file_label, 2, 0, 1, 1)
        self.settings_extract_path_line_edit = QtWidgets.QLineEdit(self.pkg_ver_group_box)
        self.settings_extract_path_line_edit.setObjectName("settings_extract_path_line_edit")
        self.gridLayout_8.addWidget(self.settings_extract_path_line_edit, 0, 1, 1, 1)
        self.settings_mnf_file_line_edit = QtWidgets.QLineEdit(self.pkg_ver_group_box)
        self.settings_mnf_file_line_edit.setObjectName("settings_mnf_file_line_edit")
        self.gridLayout_8.addWidget(self.settings_mnf_file_line_edit, 2, 1, 1, 1)
        self.settings_seven_zip_path_label = QtWidgets.QLabel(self.pkg_ver_group_box)
        self.settings_seven_zip_path_label.setObjectName("settings_seven_zip_path_label")
        self.gridLayout_8.addWidget(self.settings_seven_zip_path_label, 1, 0, 1, 1)
        self.settings_pkg_location_label = QtWidgets.QLabel(self.pkg_ver_group_box)
        self.settings_pkg_location_label.setObjectName("settings_pkg_location_label")
        self.gridLayout_8.addWidget(self.settings_pkg_location_label, 3, 0, 1, 1)
        self.settings_pkg_loc_line_edit = QtWidgets.QLineEdit(self.pkg_ver_group_box)
        self.settings_pkg_loc_line_edit.setObjectName("settings_pkg_loc_line_edit")
        self.gridLayout_8.addWidget(self.settings_pkg_loc_line_edit, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.pkg_ver_group_box)
        self.emv_version_group_box = QtWidgets.QGroupBox(settings_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.emv_version_group_box.setFont(font)
        self.emv_version_group_box.setAlignment(QtCore.Qt.AlignCenter)
        self.emv_version_group_box.setObjectName("emv_version_group_box")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.emv_version_group_box)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.settings_conf_url_label = QtWidgets.QLabel(self.emv_version_group_box)
        self.settings_conf_url_label.setObjectName("settings_conf_url_label")
        self.gridLayout_7.addWidget(self.settings_conf_url_label, 0, 0, 1, 1)
        self.settings_chrome_wd_path_label = QtWidgets.QLabel(self.emv_version_group_box)
        self.settings_chrome_wd_path_label.setObjectName("settings_chrome_wd_path_label")
        self.gridLayout_7.addWidget(self.settings_chrome_wd_path_label, 1, 0, 1, 1)
        self.settings_conf_emv_url_line_edit = QtWidgets.QLineEdit(self.emv_version_group_box)
        self.settings_conf_emv_url_line_edit.setObjectName("settings_conf_emv_url_line_edit")
        self.gridLayout_7.addWidget(self.settings_conf_emv_url_line_edit, 0, 1, 1, 1)
        self.settings_chrome_wd_line_edit = QtWidgets.QLineEdit(self.emv_version_group_box)
        self.settings_chrome_wd_line_edit.setObjectName("settings_chrome_wd_line_edit")
        self.gridLayout_7.addWidget(self.settings_chrome_wd_line_edit, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.emv_version_group_box)
        self.load_save_group_box = QtWidgets.QGroupBox(settings_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.load_save_group_box.setFont(font)
        self.load_save_group_box.setAlignment(QtCore.Qt.AlignCenter)
        self.load_save_group_box.setObjectName("load_save_group_box")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.load_save_group_box)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.settings_load_save_path_label = QtWidgets.QLabel(self.load_save_group_box)
        self.settings_load_save_path_label.setObjectName("settings_load_save_path_label")
        self.gridLayout_5.addWidget(self.settings_load_save_path_label, 0, 0, 1, 1)
        self.settings_load_save_path_line_edit = QtWidgets.QLineEdit(self.load_save_group_box)
        self.settings_load_save_path_line_edit.setObjectName("settings_load_save_path_line_edit")
        self.gridLayout_5.addWidget(self.settings_load_save_path_line_edit, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.load_save_group_box)
        self.compare_group_box = QtWidgets.QGroupBox(settings_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.compare_group_box.setFont(font)
        self.compare_group_box.setAlignment(QtCore.Qt.AlignCenter)
        self.compare_group_box.setObjectName("compare_group_box")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.compare_group_box)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.settings_compare_path_label = QtWidgets.QLabel(self.compare_group_box)
        self.settings_compare_path_label.setObjectName("settings_compare_path_label")
        self.gridLayout_6.addWidget(self.settings_compare_path_label, 0, 0, 1, 1)
        self.settings_compare_path_line_edit = QtWidgets.QLineEdit(self.compare_group_box)
        self.settings_compare_path_line_edit.setObjectName("settings_compare_path_line_edit")
        self.gridLayout_6.addWidget(self.settings_compare_path_line_edit, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.compare_group_box)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.settings_reset_push_button = QtWidgets.QPushButton(settings_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.settings_reset_push_button.setFont(font)
        self.settings_reset_push_button.setObjectName("settings_reset_push_button")
        self.horizontalLayout_3.addWidget(self.settings_reset_push_button)
        self.settings_save_push_button = QtWidgets.QPushButton(settings_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.settings_save_push_button.setFont(font)
        self.settings_save_push_button.setObjectName("settings_save_push_button")
        self.horizontalLayout_3.addWidget(self.settings_save_push_button)
        self.settings_close_push_button = QtWidgets.QPushButton(settings_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.settings_close_push_button.setFont(font)
        self.settings_close_push_button.setObjectName("settings_close_push_button")
        self.horizontalLayout_3.addWidget(self.settings_close_push_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(settings_widget)
        self.settings_close_push_button.clicked.connect(settings_widget.hide)
        QtCore.QMetaObject.connectSlotsByName(settings_widget)

    def retranslateUi(self, settings_widget):
        _translate = QtCore.QCoreApplication.translate
        settings_widget.setWindowTitle(_translate("settings_widget", "Settings"))
        self.pkg_ver_group_box.setTitle(_translate("settings_widget", "PACKAGE VERSION"))
        self.settings_extract_path_label.setText(_translate("settings_widget", "Extract Path"))
        self.settings_mnf_file_label.setText(_translate("settings_widget", "Manifest File"))
        self.settings_seven_zip_path_label.setText(_translate("settings_widget", "7-zip Path"))
        self.settings_pkg_location_label.setText(_translate("settings_widget", "Pkg Location"))
        self.emv_version_group_box.setTitle(_translate("settings_widget", "EMV VERSION"))
        self.settings_conf_url_label.setText(_translate("settings_widget", "Confluence URL"))
        self.settings_chrome_wd_path_label.setText(_translate("settings_widget", "Chrome Webdriver Path"))
        self.load_save_group_box.setTitle(_translate("settings_widget", "LOAD and SAVE"))
        self.settings_load_save_path_label.setText(_translate("settings_widget", "Path"))
        self.compare_group_box.setTitle(_translate("settings_widget", "COMPARE"))
        self.settings_compare_path_label.setText(_translate("settings_widget", "Path"))
        self.settings_reset_push_button.setText(_translate("settings_widget", "Reset"))
        self.settings_save_push_button.setText(_translate("settings_widget", "Save"))
        self.settings_close_push_button.setText(_translate("settings_widget", "Close"))
